<?php

namespace Test\ClientBundle\Repository;

/**
 * GroupClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupClientRepository extends \Doctrine\ORM\EntityRepository
{
}
